# -*- coding: utf-8 -*-
"""界面主题：深色（默认）/ 浅色"""

from __future__ import annotations

from typing import Dict

THEME_NAMES = {"dark": "深色", "light": "浅色"}

THEMES: Dict[str, Dict[str, str]] = {
    "dark": {
        "center": "#1c2030",
        "side": "#2a3048",
        "bottom": "#243044",
        "public": "#252a3a",
        "target": "#3a3228",
        "target_text": "#ffffff",
        "progress_bg": "#3a3228",
        "log_panel": "#1e2230",
        "log_bg": "#151820",
        "log_fg": "#b8c0d0",
        "dice_cell": "#3d4558",
        "dice_selected": "#4a6a4a",
        "card_locked": "#3a3a40",
        "accent": "#dcb850",
        "text": "#eeeeee",
        "text_dim": "#cccccc",
        "text_muted": "#aaaaaa",
        "text_faint": "#888888",
        "text_hint": "#aad4ff",
        "text_on_card": "#ffffff",
        "text_on_card_sub": "#fff8d0",
        "text_on_card_locked": "#bbbbbb",
        "panel_title": "#eeeeee",
        "btn_disabled_bg": "#3a3f4a",
        "btn_disabled_bar": "#555555",
        "rules_bg": "#252a3a",
        "rules_fg": "#eeeeee",
        "entry_label": "#cccccc",
        "progress_ok": "#88ff88",
        "progress_pending": "#dddddd",
        "progress_label": "#cccccc",
        "order_btn": "#4a6a9a",
        "toast_default": "#2d6a4f",
    },
    "light": {
        "center": "#ece9e1",
        "side": "#f7f4ed",
        "bottom": "#e2ddcf",
        "public": "#f1ede2",
        "target": "#f6efe1",
        "target_text": "#2c2c34",
        "progress_bg": "#f6efe1",
        "log_panel": "#ece6d8",
        "log_bg": "#ffffff",
        "log_fg": "#3f3b34",
        "dice_cell": "#ddd4bf",
        "dice_selected": "#a8c7a3",
        "card_locked": "#a89f92",
        "accent": "#8a6421",
        "text": "#2f2b25",
        "text_dim": "#4f4a42",
        "text_muted": "#6b665e",
        "text_faint": "#868076",
        "text_hint": "#5d6f8e",
        "text_on_card": "#ffffff",
        "text_on_card_sub": "#fffef5",
        "text_on_card_locked": "#f1ede4",
        "panel_title": "#2f2b25",
        "btn_disabled_bg": "#c9c2b3",
        "btn_disabled_bar": "#b8b09f",
        "rules_bg": "#ffffff",
        "rules_fg": "#2f2b25",
        "entry_label": "#4f4a42",
        "progress_ok": "#2e7a46",
        "progress_pending": "#4f4a42",
        "progress_label": "#6b665e",
        "order_btn": "#6b8db5",
        "toast_default": "#4f8968",
    },
}
