# -*- coding: utf-8 -*-
"""界面主题：深色（默认）/ 浅色"""

from __future__ import annotations

from typing import Dict

THEME_NAMES = {"dark": "深色", "light": "浅色"}

THEMES: Dict[str, Dict[str, str]] = {
    "dark": {
        "center": "#1c2030",
        "side": "#2a3048",
        "bottom": "#243044",
        "public": "#252a3a",
        "target": "#3a3228",
        "target_text": "#ffffff",
        "progress_bg": "#3a3228",
        "log_panel": "#1e2230",
        "log_bg": "#151820",
        "log_fg": "#b8c0d0",
        "dice_cell": "#3d4558",
        "dice_selected": "#4a6a4a",
        "card_locked": "#3a3a40",
        "accent": "#dcb850",
        "text": "#eeeeee",
        "text_dim": "#cccccc",
        "text_muted": "#aaaaaa",
        "text_faint": "#888888",
        "text_hint": "#aad4ff",
        "text_on_card": "#ffffff",
        "text_on_card_sub": "#fff8d0",
        "text_on_card_locked": "#bbbbbb",
        "panel_title": "#eeeeee",
        "btn_disabled_bg": "#3a3f4a",
        "btn_disabled_bar": "#555555",
        "rules_bg": "#252a3a",
        "rules_fg": "#eeeeee",
        "entry_label": "#cccccc",
        "progress_ok": "#88ff88",
        "progress_pending": "#dddddd",
        "progress_label": "#cccccc",
        "order_btn": "#4a6a9a",
        "toast_default": "#2d6a4f",
    },
    "light": {
        "center": "#e4e8f0",
        "side": "#f6f7fb",
        "bottom": "#d8dee8",
        "public": "#eef1f6",
        "target": "#faf6ef",
        "target_text": "#2c2c34",
        "progress_bg": "#faf6ef",
        "log_panel": "#e8ecf2",
        "log_bg": "#ffffff",
        "log_fg": "#3a4250",
        "dice_cell": "#d0d6e2",
        "dice_selected": "#8fbc9a",
        "card_locked": "#9a9a9a",
        "accent": "#9a7209",
        "text": "#2a2a34",
        "text_dim": "#4a4a58",
        "text_muted": "#6a6a78",
        "text_faint": "#7a7a88",
        "text_hint": "#3a5a8a",
        "text_on_card": "#ffffff",
        "text_on_card_sub": "#fffef5",
        "text_on_card_locked": "#eeeeee",
        "panel_title": "#2a2a34",
        "btn_disabled_bg": "#c8ccd4",
        "btn_disabled_bar": "#b0b4bc",
        "rules_bg": "#ffffff",
        "rules_fg": "#2a2a34",
        "entry_label": "#4a4a58",
        "progress_ok": "#1a7a3a",
        "progress_pending": "#4a4a58",
        "progress_label": "#5a5a68",
        "order_btn": "#5a8ab8",
        "toast_default": "#4a8a6a",
    },
}
